name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install builddeps
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev
        sudo pip3 install compiledb
    - name: configure
      run: ./configure --disable-docs --target-list=x86_64-softmmu
    - name: make
      run: |
        compiledb make -j $(nproc)
        sed -i 's|/home/runner/work/qemu-mirror/qemu-mirror|/Volumes/workspace/code/qemu|g' ./build/compile_commands.json

    - name: upload compile_commands.json
      uses: actions/upload-artifact@v4.6.2
      with:
        name: compile_commands.json
        path: ./build/compile_commands.json
